### ISSUE TITLE
'previous' is possibly 'undefined'

### ISSUE THREAD

**Issue by haikalariffhalim** [lucas-dash/Dynamic-Island#1]
Having issues with previous is undefined 
![xx](https://github.com/lucas-dash/Dynamic-Island/assets/137610888/fb789d22-2cf4-48d9-be5d-bfd85f0e0561)

**Comment by lucas-dash** [comment]
I don't know what could be causing it. 
Do you use Typescript or Javascript?

**Comment by haikalariffhalim** [comment]
yeah been up all night looking to solve the issue. using typescript

**Comment by lucas-dash** [comment]
yeah in the new version of framer motion is getPrevious type number | undefined. 
Try this. It should still work.
<img width="455" alt="fm-previous" src="https://github.com/lucas-dash/Dynamic-Island/assets/113235285/0353bca8-009e-49f6-865a-12640bb6a5d8">
